server:
  port: 8080
  servlet:
    context-path: /springboot-jpa
spring:
  devtools:
    restart:
      ## 热部署生效
      enabled: true
      ## 重启目录
      additional-paths: src/main/java
      ## 不重启目录
      exclude: src/main/resources

  ## 数据源
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  ## jpa
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      naming:
        naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      # 格式化sql 语句
      format_sql: true



## 日志
logging:
  level:
    com.kiritor: debug
