server:
  port: 8080
  servlet:
    context-path: /springboot

spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  ## 数据源
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  ## jpa
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      naming:
        naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      # 格式化sql 语句
      format_sql: true



## 日志
logging:
  level:
    com.kiritor: debug
