## spring
spring:
  ## 数据源
  datasource:
      url: jdbc:mysql://localhost:3306/springboot?useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 3600ms #超时时间
    lettuce:
      pool:
        max-active: 8 #最大连接数
        max-idle: 8 #最大空闲连接 默认8
        max-wait: -1ms #默认-1 最大连接阻塞等待时间
        min-idle: 0 #最小空闲连接

## mybatis
mybatis:
  type-aliases-package: com.kiritor.entity
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

## 日志
logging:
  level:
    com.kiritor.mapper: debug



